name: Deploy to Server

on:
  push:
    branches: [main]  # 当推送到 main 分支时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 检出代码仓库
    - name: Checkout code
      uses: actions/checkout@v3

    # 根据需要调整 Node.js 版本
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Create lang directory and download zh_CN language pack
      run: |
        mkdir -p node_modules/tinymce
        curl -L -o node_modules/tinymce/zh_CN.zip https://download.tiny.cloud/tinymce/community/languagepacks/6/zh_CN.zip
        unzip node_modules/tinymce/zh_CN.zip -d node_modules/tinymce/
        rm node_modules/tinymce/zh_CN.zip

    - name: Debug
      run: |
        echo "Node version:"
        node -v
        echo "NPM version:"
        npm -v
        echo "Installed packages:"
        npm list --depth=0

    # 安装依赖并打包项目
    - name: Build
      run: npm run build

    # 将文件上传到服务器
    - name: Upload to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # 定义目标服务器及文件路径
        REMOTE_USER=${{ secrets.SERVER_USERNAME }}        
        REMOTE_HOST=${{ secrets.SERVER_IP }} 
        REMOTE_PATH=${{ secrets.SERVER_PATH }}
        
        ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "rm -rf $REMOTE_PATH/*"

        # 上传文件
        scp -o StrictHostKeyChecking=no -r ./huadiao-user/* $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH
