name: Sync to Gitee

on:
  push:
    branches: [main]  # 当推送到 main 分支时触发

jobs:
  sync-to-gitee:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出代码仓库
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. 设置 Git 配置
    - name: Setup Git
      run: |
        git config --global user.name ${{ secrets.GITEE_USERNAME }}
        git config --global user.email ${{ secrets.GITEE_EMAIL }}

    # 3. 添加 Gitee 远程仓库
    - name: Add Gitee remote
      run: git remote add gitee https://${{ secrets.GITEE_USERNAME }}:${{ secrets.GITEE_TOKEN }}@gitee.com/flowerswine/huadiao-user.git

    # 4. 推送代码到 Gitee
    - name: Push to Gitee
      run: git push gitee main
